server:
  address: 121.43.49.208
logging:
  file: logs/pap.log
  level:
    root: info

jwt:
  expiration: 86400000
  secret: SHIRO_JWT
  tokenHead: "Bearer "

mail:
  to: mf1832225@smail.nju.edu.cn

pap:
  imagePath: "/root/deploy/pap/uploadImages"

spring:
  resources:
    static-locations: file:${pap.imagePath}
  mvc:
    static-path-pattern: /images/**