server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 30m
  address:
spring:
  profiles:
    active: #spring.profiles.active#
  datasource:
    url: jdbc:mysql://localhost:3306/PaintAuctionPlatform?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: ANtd79gRXzS
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 6000
      max-lifetime: 300000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  mail:
    host: smtp.exmail.qq.com
    username: mf1832225@smail.nju.edu.cn
    password: JYswdhpy8
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              fallback: false
              class: javax.net.ssl.SSLSocketFactory
    port: 465
  freemarker:
    content-type: text/html
    #后缀名
    suffix: .ftl
    template-loader-path: classpath:/templates
    charset: UTF-8
    check-template-location: true

mail:
  to:

jwt: